# # # # # # # # # # # # #
#   K i k o - p l u s   #
# # # # # # # # # # # # #

# Basic
name:               "MY LIBRARY"



author:
  name:             iamkyu
  facebook:         nkyujin
  twitter:          onoctober
  github:           iamkyu
  linkedin:         kyujinnam
  # medium:           your-id
  # tumblr:           your-id
  email:            kyujnam@gmail.com

# Google-analytics
google-analytics:
  id:               "UA-87267111-1"

# Disqus
disqus:
  id:               "my-library"

# URL
url:                "https://iamkyu.github.io" # the base hostname & protocol for your site
#url:                "http://localhost:4000" # use this url when develop
baseurl:            "" # the subpath of your site, e.g. /blog


# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:           Asia/Seoul
permalink:          /:year-:month-:day/:title/

# Pagination
paginate:           15
paginate_path:      /page:num/

# Markdown
markdown:           kramdown
kramdown:
  imput:            GFM

# Navigation
nav:
  - name:           "About"
    url:            "/about"
  - name:           "Tags"
    url:            "/tags"
  - name:           "Books"
    url:            "https://github.com/iamkyu/TIL/blob/master/book-summary/readme.md"



# Sass
sass:
  sass_dir:         _sass
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
gems:
  - jekyll-seo-tag
  - jekyll-paginate

exclude:            [vendor]
